version: '3.8'

services:
  db:
    image: postgres:15
    container_name: teampolls_db_main
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teampolls
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: teampolls_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
